apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2021-05-24T10:28:08Z
  name: dgsiaf-scenario-custom
  version: 0.1.0
  annotations:
    categories: dgsiaf-scenario-custom
    chartDescription: Injects chaos on dgsiaf-scenario-custom application
spec:
  displayName: dgsiaf-scenario-custom Chaos
  categoryDescription: >
    It install dgsiaf-scenario-custom application, inject chaos on dgsiaf-scenario-custom, uninstall the application 
    and revert the chaos
  experiments:
    - name: pod-delete
      description: "Deletes a k8s pod"
  keywords:
    - Kubernetes
    - dgsiaf-scenario-custom
    - Pod
  platforms:
    - GKE
    - Minikube
    - Packet(Kubeadm)
    - EKS
    - AKS
  maintainers:
    - name: oumkale
      email: oumkale@chaosnative.com
  provider:
    name: ChaosNative
  links:
    - name: Kubernetes Slack
      url: https://slack.kubernetes.io/
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/chaoshub/#generic-chaos
  icon:
    - url:
      mediatype: ""
